# Generated by Django 3.0.2 on 2020-02-02 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasswordrecovery',
            name='key2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_projects_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 34, 23, 510184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 34, 23, 508181, tzinfo=utc)),
        ),
    ]
