# Generated by Django 2.2.7 on 2019-11-17 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191117_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trello',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 18, 20, 1, 181284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 18, 20, 1, 180629, tzinfo=utc)),
        ),
    ]
