# Generated by Django 2.2.7 on 2019-11-26 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191126_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trello',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.URLField(default='https://t.me/', max_length=33),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 28, 6, 486618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 28, 6, 486618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.URLField(default='https://', max_length=38),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk',
            field=models.URLField(default='https://vk.com/', max_length=35),
        ),
    ]
