# Generated by Django 3.0.2 on 2020-02-02 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200202_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 46, 53, 128325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 10, 46, 53, 127325, tzinfo=utc)),
        ),
    ]
