# Generated by Django 2.2.7 on 2019-11-26 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191126_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linked_id',
            field=models.URLField(default='https://', max_length=28),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 30, 0, 547806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 30, 0, 546807, tzinfo=utc)),
        ),
    ]
