# Generated by Django 2.2.7 on 2019-12-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191224_2353'),
        ('user', '0003_auto_20191224_2230'),
    ]

    operations = [
    ]
