# Generated by Django 2.2.7 on 2020-01-19 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200119_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasswordrecovery',
            name='key2',
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 7, 38, 464465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 18, 7, 38, 462953, tzinfo=utc)),
        ),
    ]
