# Generated by Django 3.0.2 on 2020-02-02 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200202_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_commits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 35, 26, 660902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 11, 35, 26, 658903, tzinfo=utc)),
        ),
    ]
