# Generated by Django 3.0.2 on 2020-02-02 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200202_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 13, 2, 45, 106884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 13, 2, 45, 105883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
