# Generated by Django 2.2.7 on 2019-11-26 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191126_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_projects_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 18, 3, 27, 701551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 18, 3, 27, 700347, tzinfo=utc)),
        ),
    ]
