# Generated by Django 2.2.7 on 2020-01-17 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user', '0013_auto_20200110_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='useremailconfirmation',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 58, 9, 449620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userpasswordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 19, 58, 9, 448619, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
