# Generated by Django 2.2.7 on 2020-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_recruting',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(blank=True, default='Роль не задана', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProjectSkills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
