# Generated by Django 2.2.7 on 2020-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200119_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(blank=True, default='не задано', max_length=30),
        ),
    ]
