# Generated by Django 2.2.7 on 2020-02-29 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectinvite_projectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
