# Generated by Django 2.2.7 on 2019-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191217_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.CharField(default='open', max_length=6),
        ),
    ]
