# Generated by Django 2.2.7 on 2020-01-18 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200118_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collabs', to=settings.AUTH_USER_MODEL),
        ),
    ]
