# Generated by Django 3.0.2 on 2020-01-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200119_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(blank=True, default='Роль не задана', max_length=30),
        ),
    ]
