# Generated by Django 3.0.2 on 2020-02-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200129_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_recruting',
            field=models.BooleanField(default=0),
        ),
    ]
