# Generated by Django 3.0.2 on 2020-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_is_recruting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
