# Generated by Django 2.1.7 on 2019-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.IntegerField(default=True),
        ),
    ]
